"""Synthetic terminal fixtures; run only in an isolated disposable tmux session."""
import sys

if "--neighbor" in sys.argv or "--bottom" in sys.argv:
    print("MATHPEEK SYNTHETIC NEIGHBOR LOGS")
    for number in range(36):
        print(f"agent {number:02d} \u2502 tool result \u2502 unrelated $z=99$ \u2502 done")
else:
    print("MATHPEEK REGRESSION DEMO")
    print("Hover every source row; no selection is needed.")
    print()
    print("Delimited velocity:")
    print("$$")
    print(r"v_{\mathrm{pred}} =")
    print(r"v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t")
    print("$$")
    print()
    print("Raw velocity (tmux wraps this line):")
    print(r"v_{\mathrm{pred}} = v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t")
    print()
    print("One-column matrix (single slash rows):")
    print(r"\[")
    print(r"\begin{bmatrix}")
    print("v_x \\")
    print("v_y \\")
    print("v_z")
    print(r"\end{bmatrix}")
    print(r"\]")
    print()
    print("Aligned (broken spacing command):")
    print(r"\[")
    print(r"\begin{aligned}")
    print(r"p_{\mathrm{pred}} &= p_{\mathrm{prev}} + v_{\mathrm{prev}}\Delta t \[8pt]")
    print(r"v_{\mathrm{pred}} &= v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t \[8pt]")
    print(r"a_{\mathrm{world}} &= R(q)a_{\mathrm{body}} - g")
    print(r"\end{aligned}")
    print(r"\]")
    print()
    print("Codex-prompt display (stripped delimiters):")
    print("› [")
    print(r"\theta_{t+\Delta t}")
    print(r"\alpha\theta_{\text{gyro}}")
    print("+")
    print(r"(1-\alpha)\theta_{\text{acc}}")
    print("]")
    print()
    print("Markdown-heading display (stripped delimiters and heading artifacts):")
    print("# [")
    print(r"\theta")
    print(r"# 0.98\times10.6^\circ")
    print("+")
    print(r"0.02\times9^\circ")
    print(r"10.568^\circ")
    print("]")
    print()
    print("Plain stripped display:")
    print("[")
    print(r"a\longrightarrow v\longrightarrow p")
    print("]")
    print()
    print("Stripped inline matrix:")
    print(r"(i) (j) (42) (3.14) (α) (x') (x_i) (x^2) (T^{-1})")
    print(r"(W^Q_l) (W_{Q,video}) (W_{Q,audio}) (c_{\mathrm{ref}}) (10.6^\circ)")
    print(r"(x+y) (a/b) (\frac{a}{b}) (f(x)) (R(p_i)q_i) (\langle x,y\rangle)")
    print()
    print("END REGRESSION DEMO")
input("\nPress Enter to close this isolated fixture. ")
