"""Synthetic terminal fixtures; run only in an isolated disposable tmux session."""
import sys

if "--neighbor" in sys.argv or "--bottom" in sys.argv:
    print("MATHPEEK SYNTHETIC NEIGHBOR LOGS")
    for number in range(36):
        print(f"agent {number:02d} \u2502 tool result \u2502 unrelated $z=99$ \u2502 done")
else:
    print("MATHPEEK REGRESSION DEMO")
    print("Hover every source row; no selection is needed.")
    print()
    print("Delimited velocity:")
    print("$$")
    print(r"v_{\mathrm{pred}} =")
    print(r"v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t")
    print("$$")
    print()
    print("Raw velocity (tmux wraps this line):")
    print(r"v_{\mathrm{pred}} = v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t")
    print()
    print("One-column matrix (single slash rows):")
    print(r"\[")
    print(r"\begin{bmatrix}")
    print("v_x \\")
    print("v_y \\")
    print("v_z")
    print(r"\end{bmatrix}")
    print(r"\]")
    print()
    print("Aligned (broken spacing command):")
    print(r"\[")
    print(r"\begin{aligned}")
    print(r"p_{\mathrm{pred}} &= p_{\mathrm{prev}} + v_{\mathrm{prev}}\Delta t \[8pt]")
    print(r"v_{\mathrm{pred}} &= v_{\mathrm{prev}} + a_{\mathrm{world}}\Delta t \[8pt]")
    print(r"a_{\mathrm{world}} &= R(q)a_{\mathrm{body}} - g")
    print(r"\end{aligned}")
    print(r"\]")
    print()
    print("END REGRESSION DEMO")
input("\nPress Enter to close this isolated fixture. ")
